# Generated by Django 5.0.7 on 2024-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(blank=True),
        ),
    ]
